version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=tienda_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret_password
      - MYSQL_ROOT_PASSWORD=secret_password

  # Servicio de tu API Django
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      # Hot-Reload: Mapeamos la carpeta actual para que los cambios de código se reflejen sin reiniciar
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Estas variables deben coincidir con lo que espera tu settings.py
      - DB_NAME=tienda_db
      - DB_USER=root
      - DB_PASSWORD=secret_password
      - DB_HOST=db  # ¡OJO! Aquí usamos el nombre del servicio 'db' como host
      - DB_PORT=3306

# Definición del volumen persistente
volumes:
  mysql_data: