version: '3.8'

services:
  # Servicio de tu API Django
  web:
    build: .
    # CAMBIO 1: Usamos Gunicorn en lugar de runserver
    # 'Tienda' es la carpeta donde está tu wsgi.py
    command: gunicorn Tienda.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      # Tus datos de RDS MySQL
      - DB_NAME=djangodocker
      - DB_USER=admin
      - DB_PASSWORD=0325Loco*
      - DB_HOST=teis20251.cv2aqi0gc302.us-east-1.rds.amazonaws.com
      - DB_PORT=3306
      - DEBUG=1
      - ALLOWED_HOSTS=100.26.35.5,localhost,127.0.0.1
    # NOTA: No hay sección 'ports' aquí. Django está aislado.

  # CAMBIO 2: Agregamos el servicio Nginx
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"  # Nginx es el único que da la cara a internet
    volumes:
      # Inyectamos nuestro archivo de configuración
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

# No hay volumen de base de datos porque usas RDS externo