# nginx/nginx.conf

# 1. Definimos los upstreams (backends)
upstream django_v1 {
    server web_django:8000;
}

upstream flask_v2 {
    server pagos_flask:5000;
}

server {
    # Nginx escuchará en el puerto web estándar (80)
    listen 80;

    # Ignorar logs de favicon para no saturar el servidor
    location = /favicon.ico { access_log off; log_not_found off; }

    # RUTA VIEJA: Sigue yendo a Django (v1)
    location /api/v1/ {
        proxy_pass http://django_v1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # RUTA NUEVA: Estrangulamos la función de compra y la mandamos a Flask (v2)
    location /api/v2/comprar {
        proxy_pass http://flask_v2;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Cualquier otra ruta va a Django
    location / {
        proxy_pass http://django_v1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}